services:
  - type: web
    name: gemi2api-server
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    repo: https://github.com/zhiyu1998/Gemi2Api-Server
    branch: main
    envVars:
      - key: SECURE_1PSID
        sync: false
      - key: SECURE_1PSIDTS
        sync: false
      - key: API_KEY
        sync: false
      - key: FAIL_ON_STARTUP_GEMINI_ERROR
        value: "false"
      - key: GEMINI_COOKIE_PATH
        value: /var/data/gemini_webapi
    disks:
      - name: gemini-cookie-cache
        mountPath: /var/data/gemini_webapi
        sizeGB: 1
    healthCheckPath: /
    autoDeploy: true
